### ISSUE TITLE
Add bolt plan node graph feature

### ISSUE THREAD

**Issue by jpogran** [lingua-pupuli/puppet-editor-services#104]

**Comment by glennsarti** [comment]
Plans don't really have a node graph as they're procedural (manifest order) not declarative.  So the node graph option should not be available for Puppetfiles.

**Comment by glennsarti** [comment]
Nope nevermind.  Already done.

```
{
          "command": "extension.puppetShowNodeGraphToSide",
          "when": "editorLangId == 'puppet'"
        }
```
