### ISSUE TITLE
Apply not supported in plans

### ISSUE THREAD

**Issue by MikaelSmith** [lingua-pupuli/puppet-editor-services#127]
It looks like `apply` statements within Bolt plans are not parsed correctly. Below is a valid plan, but it's highlighting `class` as an error.

<img width="731" alt="Screen Shot 2019-05-22 at 2 38 17 PM" src="https://user-images.githubusercontent.com/8162496/58210923-63f29f80-7c9f-11e9-9a92-fd9adc2d8527.png">

**Comment by glennsarti** [comment]
Transferred as this is coming from puppet-lint detection, not a syntax highlighting issue

**Comment by MikaelSmith** [comment]
Ah thanks! Sorry I found the wrong repo.
