### ISSUE TITLE
Puppet Plans are not parsed correctly

### ISSUE THREAD

**Issue by genebean** [lingua-pupuli/puppet-editor-services#128]
### What Versions are you running?

Editor Name and Version: VS Code 1.33.1
Extension: 0.18.0
PDK: 1.10.0 (using embedded Puppet from this)
Puppet: 6.4.0

Document: (Include the whole document)

```puppet
plan upgrade_pe::enable_lb(
  TargetSpec $load_balancers,
) {
  $_load_balancers = $load_balancers.split(',')
  $cms = run_task('upgrade_pe::enable_lb', $_load_balancers, _catch_errors => true)
  $cms.each |$result| {
    if $result.ok {
      notice("${result.target.name} completed:\n${result.message}")
    } else {
      notice("${result.target.name} errored with message:\n${result.error}")
    }
  }
}
```

### What You Are Seeing?

Lots of red that shouldn't be there

![image](https://user-images.githubusercontent.com/966789/57464442-b9b05c00-724a-11e9-8340-ad24d704577f.png)

### What is Expected?

No red when code is correct.

### How Did You Get This To Happen? (Steps to Reproduce)

Open any plan with a `TargetSpec` defined

**Comment by glennsarti** [comment]
Transferred issue to PES as this is not a highlighting issue
