### ISSUE TITLE
Double rendering of symbols while searching

### ISSUE THREAD

**Issue by genebean** [lingua-pupuli/puppet-editor-services#173]
### What Versions are you running?

OS Version: 10.14.6
VSCode Version: 1.37.1
Puppet Extension Version: 0.20.0
Puppet Agent Version: 6.7.2
PDK Version (if applicable): 1.12.0

### What You Are Seeing?

When searching through the list of symbols it seems to be drawing things twice when used in a very large file.

### What is Expected?

A smooth, readable list

### How Did You Get This To Happen? (Steps to Reproduce)

Searched symbols in our file that creates user accounts

I will provide a screenshot privately... I can't redact the one that shows the errors.

**Comment by glennsarti** [comment]
Summarising private chat:

Looks to be a rendering issue in VS Code.

I checked the protocol and there is no setting to limit the number of symbols returned to the client.  Either in workspace of document symbols.

**Comment by glennsarti** [comment]
Relates to

https://github.com/microsoft/language-server-protocol/issues/307

https://github.com/microsoft/language-server-protocol/issues/480

https://github.com/microsoft/language-server-protocol/issues/13

**Comment by glennsarti** [comment]
For the moment @genebean  I'm going to close this issue as I don't there's anything we can do.
