### ISSUE TITLE
Automatically align => while typing or when saving

### ISSUE THREAD

**Issue by cabrinha** [lingua-pupuli/puppet-editor-services#177]
**Summary of the new feature**

Automatic => alignment, as I type, or when saving, or with a hotkey.

For example:

---
**As a** user

**I would like to** automatically automatically align `=>` as I type, or when saving, or with a hotkey.

**so that I** don't have to remember to do it myself or run lint, then go back and hit space/tab until all hashes are properly aligned.

**Comment by glennsarti** [comment]
Almost there ... lots of behind-the-scenes changes to make before I could fix the hash-rockets.

**Comment by glennsarti** [comment]
And we're merged! Will be available next release
