### ISSUE TITLE
Debugging does not stop on breakpoints

### ISSUE THREAD

**Issue by michaeltlombardi** [lingua-pupuli/puppet-editor-services#31]
### What Versions are you running?

- OS Version: W10
- VSCode Version: 
- Puppet Extension Version:
- Puppet Agent Version: 5.3.5
- PDK Version (if applicable):

### What You Are Seeing?
When using the debug functionality it does not stop on a breakpoint.

### What is Expected?
When a breakpoint is hit the code pauses.

### How Did You Get This To Happen? (Steps to Reproduce)
Create a puppet manifest with the following code:

```puppet
scheduled_task { 'Run Notepad':
  ensure   => present,
  command  => 'C:\Windows\System32\notepad.exe',
  trigger  => {
    schedule   => daily,
    start_time => '12:00',
  }
}
```

Create a debug task per instructions, set a break point on line one. Run the debugger.

### Output Log
The manifest applies without hitting the breakpoint.

**Comment by glennsarti** [comment]
Merged.  Should be fixed now.

**Comment by glennsarti** [comment]
Manually verified with @michaeltlombardi .  Closing issue.
