### ISSUE TITLE
Autocomplete should retrieve defined types and classes

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-editor-services#34]
Currently autocomplete only provides custom puppet types, not defines or classes

https://github.com/lingua-pupuli/puppet-editor-services/blob/9b19f6b6b576b1d0bdc7d56ff8971f60b171862a/lib/puppet-languageserver/manifest/completion_provider.rb#L17

https://github.com/lingua-pupuli/puppet-editor-services/blob/9b19f6b6b576b1d0bdc7d56ff8971f60b171862a/lib/puppet-languageserver/manifest/completion_provider.rb#L42

Method to enumerate things
https://github.com/lingua-pupuli/puppet-editor-services/blob/9b19f6b6b576b1d0bdc7d56ff8971f60b171862a/lib/puppet-languageserver/manifest/completion_provider.rb#L99

Ideally, this should include puppet classes and defined types from the Puppet Helper
https://github.com/lingua-pupuli/puppet-editor-services/blob/9b19f6b6b576b1d0bdc7d56ff8971f60b171862a/lib/puppet-languageserver/puppet_helper.rb#L116

**Comment by glennsarti** [comment]
Cross reference from https://github.com/lingua-pupuli/puppet-vscode/issues/225

**Comment by othalla** [comment]
would be great :)
