### ISSUE TITLE
OutlineView

### ISSUE THREAD

**Issue by jpogran** [lingua-pupuli/puppet-editor-services#56]
[VSCode 1.25](https://code.visualstudio.com/updates/v1_25#_outline-view) introduces a centralized OutlineView provider. To use this, we have to update the LanguageServer to support this provider (this ticket) as well as update the [client](https://github.com/lingua-pupuli/puppet-vscode/issues/385) to use the latest language server protocol version.

This happens to also help the [VSCode 1.2X](https://github.com/orgs/lingua-pupuli/projects/3) project as it will require updated dependencies.

The work for this ticket should be scoped to implement the following:

- [x] ~~Outlineview provider infrastructure implemented as feature toggle~~ (Not applicable now)
- [x] Show classes
- [x] Show types
- [x] Show parameters
- [x] Show variables

There are more symbols to add than this, but this is a good scoped start

**Comment by jpogran** [comment]
@glennsarti Do we still want this as a feature toggle? I'm thinking no...

**Comment by glennsarti** [comment]
Given that;
* This has `rescue` around it
* The code itself isn't too complicated
* If the symbols don't work it's not the end of the world
* Has tests
* The LSP API for this is stable

I think we can safely deploy and release this feature without a toggle.

**Comment by glennsarti** [comment]
Merged and closing.
